### ISSUE TITLE
Installing in a sub-folder doesn't work out of the box

### ISSUE THREAD

**Issue by misterben** [shaack/reboot-cms#16]
Wanted to try this out in a test environment, so I stuck it on a Dreamhost box in a sub-folder but nothing seems to be working correctly :( 

Here are my first few steps which I think have helped:

**myhost.com/rebootcms/ just gives a 404**

In the .htaccess file, change the rewrite rule to remove the leading slash from web:
`RewriteRule (.*) web/$1 [L]`

**myhost.com/rebootcms/web/ Shows the beginning of the page, but none of the assets are loading, and there is a 404 error being generated within the page (RebootCMS, Home and Documentation links are all there).**

Editing the /sites/default/template.php file so that the base reads: 
`<base href="<?= $site->getWebPath() ?>/web/" />`
and then changing all the links to be relative by removing the leading / means that the page renders with CSS and JS properly. 

I also edited the /sites/default/pages/index.md to make the image references relative, so that they would work too, but I didn't want to delve too much further. Once I started poking with the admin, I ran in to a lot of issues that I think are related. At some point I will spin up a subdomain so that I can stick it in the root folder and have it work properly :) 

Don't know if this counts as an "bug" or a "feature" - feel free to close if the plan is to only be working in the root directory.

**Comment by shaack** [comment]
Hi @misterben. Thanks for testing and making these suggestions, which helped me a lot. The reboot-cms should work now also from subdirectories.
