### ISSUE TITLE
"The page isn’t redirecting properly" when entering admin URL

### ISSUE THREAD

**Issue by binyominzeev** [shaack/reboot-cms#22]
Hi, thank you very much, really exciting project!

I just installed and looks very nice! But when I try to enter to the admin, I get this error (in Firefox):

"The page isn’t redirecting properly"

Is it possible to do something about it?

Thank you very much!

**Comment by shaack** [comment]
Hi, thank you. What is your web server?

**Comment by binyominzeev** [comment]
https://binjomin.hu/rcm/

**Comment by shaack** [comment]
Ah yes! The problem is, I think, that the website is not in the root folder, but in `/rcm`. For using the admin interface in a subfolder a code change may be necessary.

**Comment by binyominzeev** [comment]
Great, thank you! I will with a subdomain soon.
