### ISSUE TITLE
SitePath and PagePath

### ISSUE THREAD

**Issue by Epitto** [shaack/reboot-cms#29]
Hi

Of a url: https://www.sitename/namePage
I can't figure out how to return:
- https://www.sitenamesitename
- /namePage

with $request->getPath() I find /namePage

in Shaack\Reboot\Site Object:
[webPath:protected] and [baseWebPath:Shaack\Reboot\Reboot:private] are always empty.

Thanks.

**Comment by shaack** [comment]
Sorry, I cannot give such a deep support without being paid. This is only an Open Source side project and has no income.
